version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building project...
  post_build:
    commands:
      - echo Build completed on `date`
